### ISSUE TITLE
Not work on TeamSpeak  3.5.6

### ISSUE THREAD

**Issue by zsofts** [Gamer92000/TeamSpeak-3-Telegram-Bridge#4]
Not work on TeamSpeak  3.5.6
Api version is not compatible

using version 3.5.6 because there is a huge sound problem in 3.6:
https://community.teamspeak.com/t/3-6-0-sound-peaking-problem/41168

Can you recompile the latest version of your plugin for the old API?

Thank you

**Comment by Gamer92000** [comment]
See https://github.com/Gamer92000/TeamSpeak-3-Telegram-Bridge/releases/tag/v3.5.1_3.5.6
